src/getting-started/installing-rust.md
Added link to Windows installer
=> docs: Windows add link to installer

src/SUMMARY.md, src/getting-started/creating-applications.md, src/getting-started/index.md
This is still obviously incomplete, but I just wanted to get _something_ about this in the book.
[Rendered](https://github.com/esp-rs/book/blob/docs/creating-applications/src/getting-started/creating-applications.md)
=> Begin to detail the process of creating a new application

src/overview/bare-metal.md
This page was out of date, so just updated it to mention the new repositories. @bjoernQ please let me know if you feel anything important is still missing.
=> Update the page on bare metal development to mention new repositories

src/overview/bare-metal.md, src/overview/comparing-std-and-no_std.md
Hi!
Simply fixing a couple of typos while reading the book.
Great material, thank you for that!
Regards,
Bruno.
=> Fix typos.

src/installation/index.md
Feel free to update the grammar in case it is incorrect.
=> fixed a typo in installation section

src/tooling/simulating/qemu.md
It was difficult to find out how to use QEMU for simulation. Therefore I decided to add some steps, so its easier to get it working.
Let me know if any step is ambiguous or in case we need to add more explanation.
=> Add instructions for using QEMU

src/overview/index.md
=> "folling" => "following"

src/SUMMARY.md, src/installation/index.md, src/installation/troubleshooting.md, src/introduction.md, src/misc/glossary.md, src/overview/comparing-std-and-no_std.md, src/overview/using-the-standard-library.md, src/resources.md, src/tooling/debugging/vscode-debugging.md, src/tooling/espflash.md, src/tooling/simulating/qemu.md, src/tooling/simulating/wokwi.md, src/tooling/text-editors-and-ides.md, src/writing-your-own-application/generate-project-from-template.md, src/writing-your-own-application/no-std-applications/blinky.md, src/writing-your-own-application/no-std-applications/interrupt.md, src/writing-your-own-application/no-std-applications/panic.md, src/writing-your-own-application/no-std-applications/understanding-esp-template.md, src/writing-your-own-application/std-applications/index.md, src/writing-your-own-application/std-applications/understanding-esp-idf-template.md
Hi :)
I just went through the docs and fixed a number of grammar issues and markdown lint issues.
While at it, I also removed the outdated espup section on the esp-idf installation note
=> Proofread and update espup installation instructions

src/installation/index.md
Restructure the chapter Setting Up the Development Environment
=> Update Install chapter

src/installation/index.md
Massage setup section to include directions for riscv32imac-esp-espidf targets
=> Update setup section for std on riscv32imac MCUs

src/writing-your-own-application/generate-project/esp-idf-template.md, src/writing-your-own-application/generate-project/esp-template.md
=> fix typo in esp-template.md & esp-idf-template.md

src/introduction.md
Thanks @Narukara for all your effort translating the book!
=> Add Chinese translation

src/tooling/debugging/probe-rs.md, src/troubleshooting/espflash.md
- Remove rtt references
- Update troubleshooting section
=> Update probe-rs content

src/writing-your-own-application/generate-project/index.md
=> Correct typo in writing-your-own-application/generate-project/index.md

src/SUMMARY.md, src/introduction/hal-design-philosophy.md, src/introduction/hardware-overview.md, src/introduction/index.md, src/introduction/startup-flow.md, src/introduction/system-architecture.md
Still WIP and looking for input and ideas
=> Overhaul: Intro chapter

.github/workflows/ci.yml
=> Modify gha to push docs to docs.espressif.com instead

book.toml
- Remove `multilingual` field, see https://github.com/esp-rs/book/pull/190
- Update book edition to 2024
- Remove `mdbook-mermaid` stuff as we are not using it atm.
=> Remove `multilingual` field, update edition to `2024` and remove `mdbook-mermaid`

src/getting-started/toolchain.md, src/getting-started/tooling/esp-generate.md, src/getting-started/tooling/index.md, src/introduction/hal-design-philosophy.md, src/introduction/hardware-overview.md
This PR addresses the easy and initial comments of our review. 
Related to: https://github.com/esp-rs/espup/pull/499
=> Address initial review comments

src/frequently-asked-questions.md
Should cover most of the items listed in #180. Let me know if I've missed anything.
I have not addressed the comment regarding "soft bricking" of the device, as I wasn't entirely sure what this was referring to or the recommended course of action, and didn't want to just make assumptions. Once more information is provided I'm happy to take care of that as well, but probably that can be handled in another PR as the changes here (once reviewed) should be fine to merge.
=> Update FAQ chapter

.github/workflows/ci.yml
closes #221 I hope, once we redeploy
=> remove old book content on deploy
