esp-rs/book

src/getting-started/installing-rust.md
Make install docs a little more user-friendly for new rustaceans by not telling them to set rustup target.
I could see someone who is new to rustup not realizing they set their toolchain to `esp` then being confused later on when, for example, their rust version doesn't update.
=> Make install docs a little more user-friendly for new rustaceans

src/getting-started/installing-rust.md
Since I'm currently trying to force myself to use Windows 11 I was following the steps on a new system and found out the PowerShell command to download the `Install-RustToolchain.ps1` script seems to not work for me (PowerShell 7) - this fixes the command
=> Fix PowerShell command

src/SUMMARY.md, src/introduction.md, src/overview.md
The first couple commits are essentially just formatting, spelling, and clarification related updates. Just cleaning things up a little.
The most recent commit adds a section comparing the two approaches, `std` and `no_std`. While I think I've included some decent information here, I think I've sort of missed the mark. It still seems that I'm not making a compelling case for either approach. I would love to hear some suggestions on what is missing, what should be changed, etc.
A rendered view of the section in question can be seen [here](https://github.com/esp-rs/book/blob/docs/std-vs-no-std/src/overview.md#comparing-std-and-no_std).
=> Add a section comparing the `std` and `no_std` approaches

src/SUMMARY.md, src/tooling/debugging/index.md, src/tooling/debugging/openocd.md, src/tooling/debugging/probe-rs.md
* Adds some brief notes about the two most popular options for debugging
Rust applications with Espressif chips. Mostly based around the C3, as
probe-rs does not yet support any Xtensa chips.
=> debugging software for esp chips

book.toml
Add the missing icon in the same way it is used in the Rust Book.
=> Add the git repository icon to the top menu

src/overview.md
Although the std and no_std are specified in the ecosystem overview,  It is still confusing for newcomers what actual crate should be used. This PR attempts to be more specific with the relationship between the library name (std and no_std) and  the crate name.
=> Document the std and no_std repositories

src/dependencies/installing-rust.md
While following the Rust Book for ESP, I chose to take the build option for the compiler. I have been struggling to build a basic ESP example (based from [the suggested template](https://esp-rs.github.io/book/writing-your-application/generate-project-from-template.html)), encountering build errors like the following : 
```
error: unknown `--json` option `future-incompat`
```
Googling a bit, it appears that error could be linked to a too old rustc compiler. I changed the branch suggested in current documentation by the most recent branch on https://github.com/esp-rs/rust, which appears to be `esp-1.61.0.0`. Building this branch and trying to generate and build the basic template makes the error disappear.
The `esp` branch seems to be quite far behind the `esp-1.61.0.0` branch, which is, …
=> Use default branch when cloning rust compiler

src/dependencies/installing-rust.md
The default Execution Policy for Windows systems forbids execution of scripts regardless of their origin (see https://go.microsoft.com/fwlink/?LinkID=135170).
As such, we must change this, at least for the current PowerShell process. Using `-Scope Process` ensures that we don't make any persistent change.
=> Recommend Set-ExecutionPolicy Bypass before executing PowerShell scripts

src/SUMMARY.md, src/installation/troubleshooting.md
Since in `rust-build`, `espup`, `ivmarkov/rust-esp32-std-demo`, and in the templates repo we usually get some repetitive issues, I thought we could add a troubleshooting section with a short explanation and the fix for those. So we only need to share the link to the solution.
We could also update/create an issue template so users check this section before creating the issue.
Let me know if you want me to add any other common issue
=> Add troubleshooting section

src/tooling/simulating/qemu.md
Hi,
Thank you for all the work already being done, it was really helpful!
In the QEMU section, I noticed, that the command about directly calling `espflash save-image` didn't work for me.
Switching both arguments worked.
Following the reason for both commits:
1. The first commit switches the arguments and puts OUTFILE at last.
2. The second commit adds a description about the arguments being used (taken from `espflash save-image --help` )
I hope, it might be helpful. 
With best regards
Ingolf
=> QEMU: Fixing argument order and adding espflash save-image information

src/resources.md, src/writing-your-own-application/std-applications/understanding-esp-idf-template.md
The URLs for the **esp-idf-template** were pointing to the [esp-template](https://github.com/esp-rs/esp-template) repo (without std support).
Changed it to the [esp-idf-template](https://github.com/esp-rs/esp-idf-template) repo.
=> Fix URLs for esp-idf-template

src/installation/troubleshooting.md
The first path written in the subst command may not contain a backslash, see here: https://learn.microsoft.com/de-de/windows-server/administration/windows-commands/subst
This PR removes the backslash which makes the command functional. Tested on Win 11.
=> Fix `subst` path

src/installation/index.md
Links were dead when I went to use the book. This hopefully fixes them.
=> Fix install requirement page anchor links

src/writing-your-own-application/generate-project/esp-idf-template.md
The link text [esp-idf-template] was pointing to the [esp-template] repo. Correct it to match the text.
=> Correct link to esp-idf-template repo

src/tooling/simulating/qemu.md
Minor update to the espflash save-image command,
I got this error:
```
$ cargo espflash save-image --merge ESP32 outfile.bin --release
error: Found argument 'outfile.bin' which wasn't expected, or isn't valid in this context
Usage: cargo espflash save-image [OPTIONS] --chip <CHIP> <FILE>
For more information try '--help'
```
They might have changed so that --chip is needed and ESP in capital letters wasn't working for me.
=> minor espflash command update

src/overview/using-the-standard-library.md
While the table displays correctly, the *links* for `esp-idf-hal` and `esp-idf-sys` are switched around.  This simple PR fixes that.
=> fix swap of hal and sys links

src/writing-your-own-application/generate-project/esp-idf-template.md
fix typo in that "file structure"
=> fix typo in esp-idf-template.md

src/misc/troubleshooting.md
As per the discussion [here](https://matrix.to/#/!LdaNPfUfvefOLewEIM:matrix.org/$PDIMESEC-MZl46Mkr9yGKseqFzXr-920GPuwMkYgnjw?via=matrix.org&via=tchncs.de&via=mozilla.org) I think we need to remove this suggestion.
Also users got confused [here](https://github.com/esp-rs/esp-idf-sys/issues/252#issuecomment-1776380500) that `subst` would be a solution.
=> subst is not a solution for the long path names on Windows

src/installation/std-requirements.md, src/tooling/debugging/probe-rs.md
- Clarify which ESP-IDF requirements are needed for every OS
- Update some minor probe-rs stuff:
- We no longer need the `--format idf` arg
- `"channelNumber": "0",` may throw an error because it's not expecting a String.
=> Update ESP-IDF prerequisites and probe-rs improvements

src/installation/riscv.md
Explanations have been added. They explain why 'rust-src' needs to be downloaded during the environment set-up described in chapter 3.2.
below is a screenshot of the rendered output :
PS. I have just started reading this book. I am noob. I will be adding noob-like explanations to the book ( i.e explanations that I found necessary during my journey.) ✌🏼
=> additional explanations

src/writing-your-own-application/generate-project/esp-template.md
This was mostly chip agnostic already, which made this really easy! I did read through the content again though and found some outdated stuff so I addressed that here too.
Closes https://github.com/esp-rs/esp-hal/issues/1218
=> Cleanups and esp-hal references

src/SUMMARY.md, src/troubleshooting/std.md
- Remove troubleshooting/espflash section
- Fix broken link
=> Remove troubleshooting/espflash section

src/writing-your-own-application/nostd.md
`example` folder under each SOC's folder was moved to `examples`, the url pointed to `esp32c3-hal/examples` is broken. This PR removes the url, adds a description of how to check example compatibility of specific SOC.
=> Fix broken url of esp-hal example

src/writing-your-own-application/generate-project/esp-template.md
#145 updated the code snippet to remove a bunch of code that is no longer needed, but did not remove the bullet point from the explanation, making it confusing to read. it says "The next block ..." but there is no such block
=> update outdated explanation that doesn't match snippet

src/overview/index.md
This makes it clearer that ESP8266 isn't really supported
cc @MabezDev
=> Make it more clear ESP 8266 shouldn't be used

src/tooling/debugging/index.md, src/tooling/debugging/probe-rs.md
Adds a note pointing to the probe-rs Xtensa support issue
=> Add probe-rs issue link

src/tooling/visual-studio-code.md
The rust-analyzer.checkOnSave.allTargets parameter name is deprecated; VSCode highlights this as an unknown parameter (though it is still accepted by some versions of rust-analyzer). The new parameter name is rust-analyzer.check.allTargets.
=> Fix VSCode check all targets parameter name

src/overview/using-the-core-library.md
`https://github.com/esp-rs/esp-wifi#current-support` is broken.
Maybe the table was moved to `https://github.com/esp-rs/esp-hal/tree/main/esp-wifi#current-support`?
=> Fix broken link

.github/workflows/ci.yml
This is a follow up to the previous PR, which fixes the deployment and manual workflow option.
=> modify gha to push docs to docs.espressif.com instead

src/application-development/alloc.md, src/application-development/async.md, src/application-development/bootloader.md, src/application-development/configuration.md, src/application-development/index.md, src/application-development/logging.md
Also:
- If we are going to maintain `no_std-training`, the defmt stuff needs to be reorganized as atm it duplicates some information.
- Both Alloc and Logging chapters explain stuff that are already taken care in `esp-generate`. I think there is some value on explain such things, but we should clearly mark that when using `esp-generate` all that will be handled by the tool.
=> Application development improvements

src/frequently-asked-questions.md
Discussed with @MabezDev, for the time being this is all we will add to the FAQ which is not already present. Remaining points can be added in the future, but this will close #179.
=> Add a section to the FAQ regarding use of `mem::forget`

src/overview/using-the-core-library.md
The original link (https://github.com/esp-rs/esp-hal/tree/main/esp-wifi#current-support) is dead, and instead needs to go to the right repository (`esp-radio`, and not `esp-wifi` since it was renamed).
Refering to the hyperlink in the book shown here:
=> Fix hyperlink (after `esp-wifi` -> `esp-radio` repo rename)
